// <auto-generated />
namespace GO.Infra.SqlServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class f : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f));
        
        string IMigrationMetadata.Id
        {
            get { return "201503242152057_f"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
